sudo: false
language: node_js
node_js:
  - "14.0"

services:
  - redis-server
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS tpm_test;"
  - "npm install -g grunt-cli"
  - "npm install -g bower"

install:
  - "npm install"
  - "bower install"

before_script:
  - echo "USE mysql;" | mysql -u root
  - grunt build
  - grunt
