sudo: false
language: node_js
node_js:
    - "8.0"

services:
    - redis-server

before_install:
    - "npm install -g grunt-cli"
    - "npm install -g bower"

install:
    - "npm install"
    - "bower install"

before_script:
    - mysql -e "create database IF NOT EXISTS tpm_test;"
    - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
    - grunt build
    - grunt
